### PR TITLE
Feature/relax `Unpin` for `ReadEnd`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
I don't think I have the context necessary to review everything in here unfortunately — I'm not familiar enough with the `openssh-sftp-client` code base :)

**Comment by NobodyXu** [comment]
> I don't think I have the context necessary to review everything in here unfortunately — I'm not familiar enough with the `openssh-sftp-client` code base :)

That's understandable since I mostly wrote these stuff myself.

If you feel uncomfortable, I can refrain from adding you as a reviewer in this crate.

**Comment by NobodyXu** [comment]
So a brief summary of this pr is that it removes `Unpin` bound for the `lowlevel::ReadEnd`, expose two new methods so that `ReadEnd` can be used without `Unpin` bound:
 - `lowlevel::connect_with_auxiliary_relaxed_unpin`
 - `lowlevel::ReadEnd::receive_server_hello_pinned`

And unlike the last PR, this one doesn't add more types (no `unsafe` code or new pin utilities), so it should be less likely to have unsoundness.

P.S. I should probably try to provide a better summary next time when opening a new PR.

**Comment by NobodyXu** [comment]
This is basically a follow-up PR for #8

**Comment by NobodyXu** [comment]
@jonhoo Just to let you know in case you want to review/comment, I plan to merge this tomorrow.

**Pull request merged**
