### PR TITLE
Remove annoying lifetime in `{fs, file}::*`

### LINKED ISSUE #63: Is it possible to remove lifetime from `File`?
Hi, is it possbile to remove the lifetime from `File` so that users don't need to hack them?

To allow using `File` like `std::fs::File`/`tokio::fs::File`, we have to do something like the following:

https://github.com/apache/incubator-opendal/blob/main/core/src/services/sftp/utils.rs#L39-L66

```shell
pub struct SftpReader {
    // similar situation to connection struct
    // We can make sure the file can live as long as the connection.
    file: OwningHandle<
        Box<PooledConnection<'static, Manager>>,
        Box<FdReader<Compat<TokioCompatFile<'static>>>>,
    >,
}

impl SftpReader {
    pub async fn new(
        conn: PooledConnection<'static, Manager>,
        path: PathBuf,
        start: u64,
        end: u64,
    ) -> Result<Self> {
        let mut file = OwningHandle::new_with_fn(Box::new(conn), |conn| unsafe {
            let file = block_on((*conn).sftp.open(path)).unwrap();
            let f = Compat::new(TokioCompatFile::from(file));
            Box::new(oio::into_reader::from_fd(f, start, end))
        });

        file.seek(SeekFrom::Start(0)).await?;

        Ok(SftpReader { file })
    }
}
```

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #63

### CODE REVIEW

**Comment by NobodyXu** [comment]
@Xuanwo @silver-ymz I've removed all lifetime in `{fs, file}::*`.

Can you review this PR, have a look at the new API and see if works for you?

**Comment by silver-ymz** [comment]
Thanks a lot. `opendal` seems to require `file` to impl `UnPin`. Now I'am confusing about it. Could you wait me do more research, and then give a response?

**Comment by NobodyXu** [comment]
> Thanks a lot. `opendal` seems to require `file` to impl `UnPin`.

`openssh_sftp_client::file::File` is `Unpin` just as before.

It's `openssh_sftp_client::file::TokioCompatFile` that is now `!Unpin` since I replaced the `Pin<Box<WaitForCancellationFuture<'sftp>>>` with `WaitForCancellationFutureOwned` so that user can decide whether to box `TokioCompatFile` for maximum efficiency.

You can still use a `Box::pin` so that you can use `AsyncWriteExt`/`AsyncReadExt`/`AsyncReadBufExt` and use it with ease.

> Now I'am confusing about it. Could you wait me do more research, and then give a response?

Sure, takes your time.
I'm not in a rush to release it.

Taking time to get it right is always better than rushing PRs.

**Comment by Xuanwo** [comment]
If it possible for `Sftp` to hold a `session` and spawn command (which means hold on `RemoteChild`) internally? So that users don't need to hold `session`, `remote_child` and `Sftp` at the same time. To avoid `RemoteChild` been dropped earlier than `Sftp`, users like opendal have to use `owning_ref` tricks.

How we use `openssh` & `sftp-client` for now:

```rust
let session = session.connect(self.endpoint.clone()).await?;

let sess = Box::new(session);
let mut oref = OwningHandle::new_with_fn(sess, unsafe {
    |x| {
        Box::new(
            block_on(
                (*x).subsystem("sftp")
                    .stdin(Stdio::piped())
                    .stdout(Stdio::piped())
                    .spawn(),
            )
            .unwrap(),
        )
    }
});

let sftp = Sftp::new(
    oref.stdin().take().unwrap(),
    oref.stdout().take().unwrap(),
    Default::default(),
)
.await?;
```

Possible problems:

- We have to box session.
- we have to call `block_on` which could make everything more complex while intereact with tokio runtime
- we have to use `owning_ref` tricks
- Very easy to be used in wrong (drop `RemoteChild` after building `Sftp`)

What's I expected:

```rust
let session = session.connect(self.endpoint.clone()).await?;
let sftp = SftpX::with_session(session).await?;
```

`SftpX` should handling the drop of `RemoteChild` and `Session` internally.

---

What do you think? Also cc @silver-ymz for ideas.

**Comment by NobodyXu** [comment]
> If it possible for Sftp to hold a session and spawn command (which means hold on RemoteChild) internally? So that users don't need to hold session, remote_child and Sftp at the same time. To avoid RemoteChild been dropped earlier than Sftp, users like opendal have to use owning_ref tricks.

@Xuanwo That's a really good idea!
I would definitely add it, though again it would break `Sftp` API and the `Sftp::close` API.

**Comment by silver-ymz** [comment]
> Can you review this PR, have a look at the new API and see if works for you?

Great. This new API works very well for us. I have completed the work of adapting to the new API in https://github.com/apache/incubator-opendal/pull/2192. Now `opendal` just wait this release.

**Comment by NobodyXu** [comment]
@Xuanwo @silver-ymz I've added a new function `Sftp::new_with_auxiliary`.

Not that ideal as `Sftpx` as you still need to pass stdin, stdout, options and the remote-child separately, but it does the dropping for you:

<details>
```rust
let session = session.connect(self.endpoint.clone()).await?;

let sess = Box::new(session);
let mut oref = OwningHandle::new_with_fn(sess, unsafe {
    |x| {
        Box::new(
            block_on(
                (*x).subsystem("sftp")
                    .stdin(Stdio::piped())
                    .stdout(Stdio::piped())
                    .spawn(),
            )
            .unwrap(),
        )
    }
});

let sftp = Sftp::new_with_auxiliary(
    oref.stdin().take().unwrap(),
    oref.stdout().take().unwrap(),
    Default::default(),
    SftpAuxiliaryData::Some(Box::new(oref)),
)
.await?;

Ok(Connection {
    sftp,
})
```

</details>

This is actually a flaw of `openssh`.
I can submit a separate PR to add a new type `RemoteChildOwned` possible, or perhaps I can revamp the entire crate to remove use of lifetime.

@Xuanwo @silver-ymz I recommend you to open an issue in openssh to discuss this with @jonhoo and see what's his thoughts on this.

Also, I'm adding support to new proxy-mode to openssh-mux-client https://github.com/openssh-rust/openssh-mux-client/issues/6 , which will enable you to use stdin/stdout/stderr while dropping `Session` and `RemoteChild`.

It will also support windows.

Unfortunately, it was blocking on `tokio_util::sync::WaitForCancellationFutureOwned`, so I switched to other projects and I kind of forgot it.
I will restart working on it, but it will takes quite some time before it's ready to use.

**Comment by Xuanwo** [comment]
Thanks a lot! There is not a rush for the new lifetime-free API. I think we can merge https://github.com/openssh-rust/openssh-sftp-client/pull/65/commits/f8047a13ac5e22b318ad548a8994f777e89f9063 first and cut new release. After that, we can polish https://github.com/openssh-rust/openssh-sftp-client/pull/65/commits/8b380aa3a9ebde5c0a9f5a1fe3fde9975c74333a for a better API.

**Comment by NobodyXu** [comment]
@Xuanwo You can also replace `tokio::spawn` with `Box::pin` for less overhead:

<details>

```rust
let (tx, rx) = tokio::sync::oneshot::channel();

let mut future = Box::pin(async move {
    let (_child, stdin, stdout) = spawn_child(&session).await?;
    tx.send((stdin, stdout)).ok();
    // Wait forever until being dropped
    std::future::pending().await
});

let (stdin, stdout) = tokio::select! {
   // Always poll future first to simplify branches
   biased;

    // future would only return on error
    res = future.as_mut() => return Err(res.unwrap_err().into()),
    // future would either error, or enter pending() now,
    // so tx.send is already done and awaiting on rx should always succeed.
    res = rx => res.unwrap(),
};

let sftp = Sftp::new_with_auxiliary(
    stdin,
    stdout,
    Default::default(),
    SftpAuxiliaryData::Some(Pin::into_inner(future)),
)
.await?;

Ok(Connection {
    sftp,
})
```

</details>

**Comment by Xuanwo** [comment]
> You can also replace `tokio::spawn` with `Box::pin` for less overhead:

learnt a lot!

**Comment by NobodyXu** [comment]
@Xuanwo @silver-ymz Please do a final review of this PR, especially the API and I will merge this tomorrow.

**Review by Xuanwo — APPROVED** [review]
Mostly LGTM, let's have a try!

**Review by silver-ymz — APPROVED** [review]

**Pull request merged**
