### PR TITLE
Implement `Sftp::from_clonable_session*`

### LINKED ISSUE #130: Trying to create a file over SFTP results in BackgroundTaskFailure
```called `Result::unwrap()` on an `Err` value: BackgroundTaskFailure("read/flush task failed")```

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #130

### CODE REVIEW

**Comment by NobodyXu** [comment]
cc @kanpov can you have a try of this PR please?

**Comment by kanpov** [comment]
@NobodyXu `the trait bound: openssh::Session: Deref is not satisfied`

**Comment by NobodyXu** [comment]
cc @kanpov It's meant to be used with `Arc<Session>`, so that you can reuse the session elsewhere.

**Comment by kanpov** [comment]
@NobodyXu By creating an arc of the session, and cloning the arc and passing the clone into `from_cloneable_session`, everything works

**Pull request merged**
